FROM php:8.4-fpm-alpine

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd bcmath zip redis xdebug pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
